BUILD: Resync rpmbuild-docker script to fix el7 repos since EOL

diff --git a/rpmbuild-docker b/rpmbuild-docker
--- a/rpmbuild-docker
+++ b/rpmbuild-docker
@@ -30,6 +30,17 @@ function version() {
   echo "${PROGFILE##*/}${VERSION:+ $VERSION} - $AUTHOR - $LICENSE"
 }
 
+function on_exit() {
+  if [[ -n $GITREV && $SPECFILE == *.gitrev ]]; then
+    rm -f "$SPECDIR/$SPECFILE"
+  fi
+  if [[ -n $GIT_ARCHIVE_TMP && -d $GIT_ARCHIVE_TMP ]]; then
+    rm -rf "$GIT_ARCHIVE_TMP"
+  fi
+}
+
+trap on_exit EXIT
+
 declare QUIET=$QUIET
 declare VERBOSE=$VERBOSE
 declare XDEBUG=$XDEBUG
@@ -41,11 +52,14 @@ declare REPO=$REPO
 declare UPDATE=
 declare KEEP=
 declare NOKEEP=
+declare GITREV=
 declare SOURCEDIR=$SOURCEDIR
 declare OUTPUTDIR=$OUTPUTDIR
 declare PREBUILDSCRIPT=$PREBUILDSCRIPT
 declare DOWNLOAD=1
+declare RPMOPTS=()
 declare RPMBUILDOPTS=()
+declare RPMSPECOPTS=()
 
 if [[ -n $VERBOSE ]] ; then
   ( IFS='' ; echo "[DEBUG] '${0}${*/#/' '}'" )
@@ -79,6 +93,8 @@ while (( $# > 0 )); do
     --keep) KEEP=1 ;;
     ## --nokeep: never keep build environment on error
     --nokeep) NOKEEP=1 ;;
+    ## --gitrev: create source0 tarball from git revision
+    --gitrev) GITREV=$2 ; shift ;;
     # generic args
     --) shift ; break ;;
     -*) usage "Unknown parameter '$1'" && exit 1 ;;
@@ -89,7 +105,7 @@ done
 
 [[ $XDEBUG == 1 ]] && set -x
 
-RPMBUILDOPTS+=( "$@" )
+RPMOPTS+=( "$@" )
 
 declare SPECFILE=${ARGS[0]}
 [[ ${SPECFILE:0:1} != "/" ]] && SPECFILE=$PWD/$SPECFILE
@@ -123,23 +139,27 @@ if [[ -z $SOURCEDIR && -d ${SPECDIR%/*}/SOURCES ]] ; then
   SOURCEDIR=${SPECDIR%/*}/SOURCES
 fi
 
-if [[ -z $PREBUILDSCRIPT ]]; then
+if [[ -n $PREBUILDSCRIPT ]]; then
+  [[ ${PREBUILDSCRIPT:0:1} == / ]] || PREBUILDSCRIPT="$PWD/$PREBUILDSCRIPT"
+elif [[ -z $PREBUILDSCRIPT ]]; then
   # auto locate prebuild script if not given
-  if [[ -x $SPECDIR/prebuild.sh ]]; then
-    PREBUILDSCRIPT=$SPECDIR/prebuild.sh
-    PREBUILDSCRIPTFILE=prebuild.sh
-  elif [[ -x ${SPECDIR%/*}/prebuild.sh ]]; then
-    PREBUILDSCRIPT=${SPECDIR%/*}/prebuild.sh
-    PREBUILDSCRIPTFILE=prebuild.sh
-  else
-    PREBUILDSCRIPTFILE=
-  fi
-else
-  if [[ ! -x $PREBUILDSCRIPT ]]; then
-    echo "FATAL: cannot execute prebuild script: $PREBUILDSCRIPT" >&2
+  for dir in "$SPECDIR" "$PWD"; do
+    for ext in sh inc; do
+      if [[ -e "$dir/prebuild.$ext" ]]; then
+        PREBUILDSCRIPT="$dir/prebuild.$ext"
+        break 2
+      fi
+    done
+  done
+fi
+if [[ -n $PREBUILDSCRIPT ]]; then
+  if [[ ! -r $PREBUILDSCRIPT ]]; then
+    echo "FATAL: can't open $PREBUILDSCRIPT for reading" >&2
+    exit 1
+  elif [[ ${PREBUILDSCRIPT##*.} == .sh && ! -x $PREBUILDSCRIPT ]]; then
+    echo "FATAL: prebuild script $PREBUILDSCRIPT not executable" >&2
     exit 1
   fi
-  PREBUILDSCRIPTFILE=${PREBUILDSCRIPT##*/}
 fi
 
 [[ -z $SOURCEDIR ]] && SOURCEDIR=$PWD
@@ -198,6 +218,7 @@ function dockerfile_for_dist_el7() {
 FROM centos:7
 RUN set -x && \
     ulimit -n 1024 && \
+    sed -i -re 's,mirror\.centos\.org,vault.centos.org,; s,^(mirrorlist),#\1,; s,^#(baseurl),\1,' /etc/yum.repos.d/CentOS-*.repo && \
     yum update -y && \
     yum install -y createrepo gcc make rpm-build && \
     echo '* - nproc 2048' >> /etc/security/limits.d/90-nproc.conf && \
@@ -334,6 +355,51 @@ then
   RPMBUILDOPTS+=( --noclean )
 fi
 
+# Prepare env and script to be run inside the container
+BGROUP=$(id -gn)
+BUSER=${USER:-$(id -un)}
+BHOME=~
+
+# Handle $GITREV:
+# - create a source tarball from the current directory, assuming it is a git
+# - use it as source0
+# - change version accordingly (git describe) in spec file
+
+# $1: git rev
+# $2: output filename without extension (.tar.gz auto added)
+# $3: prefix without trailing slash
+function git_archive_mtime() {
+  GIT_ARCHIVE_TMP=$(mktemp -d) || return 1
+  git archive --format tar --prefix "$3/" \
+    "$1" ./ ':!rpmbuild-docker' ':!*.spec' ':!SPECS/' |
+    tar x -C "$GIT_ARCHIVE_TMP/" || return 1
+  find "$GIT_ARCHIVE_TMP/$3/" -not -type d -printf '%P\n' |
+    xargs -n 1 -I{} sh -c 'touch -d "$(git log --pretty=format:%ci -n 1 "$1" -- "$3")" "$2/$3"' -- \
+      "$1" "$GIT_ARCHIVE_TMP/$3/" {} || return 1
+  tar czf "$2.tar.gz" -C "$GIT_ARCHIVE_TMP/" "$3"
+}
+
+function gitrev2rpm() {
+  local gitdesc gitdate
+  gitdesc=$(git describe --tags --match 'v?*' --abbrev=7 --always "$1")
+  if [[ $gitdesc =~ ^(v(.+)(-[0-9]+-g))?([0-9a-f]+)$ ]]; then
+    gitdate=$(date -d "$(git log -n 1 --format='%ci' "$1")" +%Y%m%d%H%M%S)
+    REPLY=( "${BASH_REMATCH[2]:-0.0.0}^${gitdate}g${BASH_REMATCH[4]}.${BUSER:0:3}" "${BASH_REMATCH[4]}" )
+  else
+    REPLY=( "${gitdesc:1}" "${gitdesc:1}" )
+  fi
+}
+
+if [[ -n $GITREV ]]; then
+  gitrev2rpm "$GITREV"
+  project=${PWD##*/}
+  sed -re "s,(^\\s*Version\\s*:\\s*).*,\\1${REPLY[0]}," \
+    -e "s|(^\\s*source0\\s*:\\s*).*|\\1$project-dev.tar.gz|i" \
+    "$SPECDIR/$SPECFILE" > "$SPECDIR/$SPECFILE.gitrev"
+  SPECFILE="$SPECFILE.gitrev"
+  git_archive_mtime "$GITREV" "$SOURCEDIR/$project-dev" "$project-${REPLY[1]}"
+fi
+
 # Options for docker
 DOCKER_OPTS=(
   "${DOCKER_OPTS_DIST[@]}"
@@ -352,16 +418,12 @@ if [[ -n $REPO ]] ; then
 fi
 
 if [[ -n $PREBUILDSCRIPT ]] ; then
-  DOCKER_OPTS+=( --mount "type=bind,src=$PREBUILDSCRIPT,dst=/tmp/$PREBUILDSCRIPTFILE" )
+  DOCKER_OPTS+=( --mount "type=bind,src=$PREBUILDSCRIPT,dst=/tmp/${PREBUILDSCRIPT##*/}" )
 fi
 
-# Prepare env and script to be run inside the container
-BGROUP=$(id -gn)
-BUSER=${USER:-$(id -un)}
-BHOME=~
 
 function build_exit() {
-  local status=${1:-0}
+  local status=${?:-0}
   [[ -n $NOKEEP ]] && exit "$status"
   [[ -n $KEEP || $status != 0 ]] && sleep infinity
   exit "$status"
@@ -386,7 +448,8 @@ function build_dl() {
   fi
 }
 function build_main() {
-  set -fx
+  set -fxe
+  trap build_exit EXIT
   OIFS=$IFS
 
   mkdir -p "$BHOME"
@@ -406,34 +469,40 @@ EOF
     fi
   fi
 
-  if [[ -n $PREBUILDSCRIPTFILE ]] ; then
-    "/tmp/$PREBUILDSCRIPTFILE" || build_exit $?
+  if [[ -n $PREBUILDSCRIPT ]]; then
+    case "$PREBUILDSCRIPT" in
+      *.sh) "/tmp/$PREBUILDSCRIPT" ;;
+      *.inc) source "/tmp/$PREBUILDSCRIPT" ;;
+      *) echo 'Invalid prebuild script/source file'; exit 1 ;;
+    esac
   fi
 
+  RPMOPTS+=(  --define '_topdir /tmp/../tmp/../tmp' )
+  rpmbuildopts=( "${RPMOPTS[@]}" "${RPMBUILDOPTS[@]}" )
+  rpmspecopts=( "${RPMOPTS[@]}" "${RPMSPECOPTS[@]}" )
+
   IFS=$'\n'
-  buildreq=( $(rpmspec -P "/tmp/$SPECFILE" |
+  buildreq=( $(rpmspec -P "/tmp/$SPECFILE" "${rpmspecopts[@]}" |
     sed -ne 's/^BuildRequires: *//p' |
     sed -re 's/(( +[^ ,]|[^ ,])*),/\1\n/g' |
     sed -re 's/^ *([^ ]( +[^ ]|[^ ])*) *$/\1/') )
   IFS=$OIFS
   if [[ -n $buildreq ]]; then
-    yum install -y "${buildreq[@]}" || build_exit $?
+    yum install -y "${buildreq[@]}"
   fi
 
   # download sources if needed
   if [[ $DOWNLOAD == 1 ]] ; then
-    dlsources=( $(rpmspec -P "/tmp/$SPECFILE" |
+    dlsources=( $(rpmspec -P "/tmp/$SPECFILE" "${rpmspecopts[@]}" |
       sed -nr -e 's,^(source|patch)[0-9]*\s*:\s*(\S+).*,\2,i;T;/:\/\//p') )
     for i in "${dlsources[@]}"; do
-        RUNAS="$BUSER" build_dl "$i" /tmp/SOURCES || build_exit $?
+        RUNAS="$BUSER" build_dl "$i" /tmp/SOURCES
     done
   fi
 
   # Having _topdir /tmp causes problems in el6/el7 because it is not long enough
   # https://access.redhat.com/solutions/1426113
-  build_runas "$BUSER" rpmbuild --define '_topdir /tmp/../tmp/../tmp' \
-    --define "dist .$DIST" "${RPMBUILDOPTS[@]}" -ba "/tmp/$SPECFILE" ||
-      build_exit $?
+  build_runas "$BUSER" rpmbuild "${rpmbuildopts[@]}" -ba "/tmp/$SPECFILE"
 
   if [[ -n $REPO && -n $UPDATE ]] ; then
     for repo in RPMS SRPMS; do
@@ -441,7 +510,6 @@ EOF
       build_runas "$BUSER" createrepo --update "/tmp/local-repo/$repo"
     done
   fi
-  build_exit 0
 }
 
 # Build RPM in the container
@@ -449,7 +517,8 @@ CTNAME="build_${RANDOM}${RANDOM}${RANDOM}${RANDOM}"
 DOCKER_OPTS+=( --name "$CTNAME" -i --rm )
 trap 'docker kill "$CTNAME"; exit;' INT
 cat <<__EOF__ |docker run "${DOCKER_OPTS[@]}" "$IMAGE" /bin/bash &
-$(declare -p BGROUP BHOME BUSER DIST DIST_TYPE DIST_VERSION DOWNLOAD KEEP NOKEEP PREBUILDSCRIPTFILE REPO RPMBUILDOPTS SPECFILE UPDATE)
+$(declare -p BGROUP BHOME BUSER DIST DIST_TYPE DIST_VERSION DOWNLOAD KEEP NOKEEP REPO RPMOPTS RPMBUILDOPTS RPMSPECOPTS SPECFILE UPDATE)
+$(printf 'PREBUILDSCRIPT=%q\n' "${PREBUILDSCRIPT##*/}")
 $(declare -f build_exit)
 $(declare -f build_runas)
 $(declare -f build_dl)
